### ISSUE TITLE
기능 요청: eslint rule 추가

### ISSUE THREAD

**Issue by timepresent95** [dm-plz/family-farm-mobile#13]
## 기능 설명
코드 내 공백 관련 다음 eslint rule 추가
```
"rules": {
  "space-before-function-paren": ["error", "always"],
  "space-before-blocks": ["error", "always"],
  "object-curly-spacing": ["error", "always"]
}
```
## 기대 효과
가독성 향상

**Comment by porporpor020202** [comment]
<img width="722" alt="Screenshot 2024-08-07 at 2 33 55 PM" src="https://github.com/user-attachments/assets/ed95e658-8d35-44fa-8149-bc199b82f3ce">
<img width="619" alt="Screenshot 2024-08-07 at 2 34 10 PM" src="https://github.com/user-attachments/assets/55d6dd67-4466-426d-83e8-74b7ee937315">

prettier 설정과 충돌함. 확인 바람

**Comment by porporpor020202** [comment]
enslint 설정대로 하고싶은거면 컨펌해주면, .prettier도 내가 수정해놓을께

**Comment by timepresent95** [comment]
@porporpor020202
프리티어랑 출돌나면 eslint 설정 > extends > prettier가 자동으로 eslint 우선 적용해줘서 수정은 안해도 되는데
모호해서 혼동되면 수정하는것도 좋아!

**Comment by porporpor020202** [comment]
@timepresent95 
그렇게 하면 
"space-before-function-paren": ["error", "always"],
  "space-before-blocks": ["error", "always"],
  "object-curly-spacing": ["error", "always"]
 이 룰대로 포메팅이 안되자넝

수정해놓고 포매터도 한번 돌려놓을께

**Comment by porporpor020202** [comment]
""space-before-function-paren": ["error", "always"]," 이 옵션은 계속 적용이 안되네.

prettier 2버전 미만일땐 설정 옵션이 있었는데, 그 이후에는 저거 설정하는 옵션이 빠졌다는데?
그리고 현재 계속 설정 옵션을 찾고있는데, 검색이 안되네.

(https://prettier.io/docs/en/options)
(https://github.com/prettier/prettier-vscode/issues/494)
위 자료들을 참고해봤는데, spaceBeforeFunctionParen 옵션 자체가 없어.

<img width="596" alt="Screenshot 2024-08-07 at 4 55 44 PM" src="https://github.com/user-attachments/assets/620c7b9f-40bf-43fa-92c6-7eb3fbfd7860">

그리고 space를 parentheses 앞에 추가하면, eslint에서 위 오류가 생겨.
저거 해결법도 찾고있는데, 지금 검색한 내용으론 저거 해결하려면 eslint 설정 자체 바꿔야하고, 그러려면 꽤 오랜시간이 필요할거같애.

결론적으로.. 저 옵션을 적용하려면
(1) prettier에서 spaceBeforeFunctionParen 적용법 찾기
(2) eslint에서 prettier/prettier 오류 생기는 것 해결법 찾기
위 두개를 해결해야해.

따라서 이 옵션은 지금 당장 내가 수정하기엔 난이도가 있는데,  
"space-before-function-paren": ["error", "always"],
이 옵션은 제외하면 어떨까? 아니면 혹시 해결 방법을 알고있을까?

**Comment by timepresent95** [comment]
@porporpor020202  
이해했어 충돌나서 지금 안된다는거지?
그 잘 적용이 안되면 해당 코드만 좀 보여줄수 있을까?
아니면 내가 해당 부분 한번 더 할게 이 이슈 닫지말고 현재 적용된 내용까지만 push 해줘

**Comment by porporpor020202** [comment]
@timepresent95 
#23 여기에 push했어.

**Comment by timepresent95** [comment]
https://github.com/dm-plz/family-farm-mobile/issues/13#issuecomment-2272856585

위 내용에 명시되어 있듯이 
eslint "space-before-function-paren" 설정과 반대되는 prettier 설정을 변경할수 없음

이에 space-before-function-paren 설정을 제외하기로 함

나머지 내용은 #23 PR에서 전부 해결함
