### ISSUE TITLE
빌드: react-navigation 라이브러리 설치

### ISSUE THREAD

**Issue by porporpor020202** [dm-plz/family-farm-mobile#14]
## 빌드 설명
react-navigation/native 을 설치하려 함.

## 기대 효과
라우팅 기능 구현을 위함.

## 추가 정보
npm ci이후, ios폴더에서 bundle exec pod install 해야함.

**Comment by timepresent95** [comment]
#3 할때 라이브러리 사용 안했어?

**Comment by porporpor020202** [comment]
PR 올릴때, 이거랑 #3 이랑 같이 올릴 생각이야.
이건 빌드고, #3 은 기능추가니까 분리해서 이슈로 만들었어.

**Comment by timepresent95** [comment]
@porporpor020202 
PR 올릴때, 이거랑 https://github.com/dm-plz/family-farm-mobile/issues/3 이랑 같이 올릴 생각이야.
이건 빌드고, https://github.com/dm-plz/family-farm-mobile/issues/3 은 기능추가니까 분리해서 이슈로 만들었어.
-> 이렇게 하는거 좋아 ㅎㅎ 만들어줘서 고마워~
