### ISSUE TITLE
빌드: react-native-svg 설치

### ISSUE THREAD

**Issue by porporpor020202** [dm-plz/family-farm-mobile#16]
## 빌드 설명

react-native-svg

https://github.com/software-mansion/react-native-svg

## 기대 효과
로컬에 SVG 파일을 저장후 사용 할 수 있게 됨.

## 추가 정보

React-Native 
<img width="589" alt="Screenshot 2024-08-01 at 10 30 07 PM" src="https://github.com/user-attachments/assets/5121d88a-88e0-4235-8d7e-a8e22a1022c4">

생년월일 음력 체크 버튼 구현을 위해 Checkbox가 필요하나,
RN에서 Checkbox 컴포넌트 삭제됨.

라이브러리도 알아보았으나, SVG 파일로 직접 구현하는 게 오히려 편할지도 모르겠다 싶음.
https://docs.google.com/spreadsheets/d/1IgPfdY9ohwr6Pzf4EOwrvqehT5IwT0rK3UCbGGaZ2ZQ/edit?gid=0#gid=0

**Comment by timepresent95** [comment]
체크 박스같은 경우에는 우선 pressbutton 같은거로 임시 구현 하고
라이브러리는 추후에 결정하자
디자이너가 어떤거 주냐에 따라 달라질것 같아서 굳이 의존성을 추가하지 않는게 좋을것같아

동의 하면 close 해주고 아니면 코멘트 추가해줘

정보 공유 고마워!

**Comment by porporpor020202** [comment]
같은 생각이야. 체크하면 오렌지 뜨게 만들어놨음 ㅋㅋ
