### ISSUE TITLE
기능 요청: 라우팅 페이지 순서 변경, Join페이지 접속 버튼 생성

### ISSUE THREAD

**Issue by porporpor020202** [dm-plz/family-farm-mobile#26]
## 기능 설명
앱 개발이 완전히 끝난뒤, 정상적인 앱 사용 순서는 다음과 같다.
1. 사용자가 앱스토어에서 앱 설치
2. 사용자가 앱을 키면, Onboarding 페이지가 뜸
4. 사용자가 카카오, ios, google 로그인 중 선택해서 로그인 함
5. 로그인 완료되면, BottomTopNavigator가 뜸.
6. 이후 사용자가 앱을 사용함.

그러나 현재처럼 앱 개발중인 상황에선, Onboarding 페이지를 띄워버리면, Join페이지로 넘어갈 수가 없음.
그래서 바로 Join 페이지로 넘어가는 버튼을 생성함.

## 기대 효과
Join페이지 바로 진입 가능으로 인해, 로그인 기능 구현 전에도 앱 개발 가능.
+ 이후 로그인 기능 구현 후에도 바로 기능을 앱에 적용하기 쉬워짐

**Comment by timepresent95** [comment]
@porporpor020202
onBoarding은 로그인 또는 회원가입도 로직이라서 별도의 버튼은 불필요한것같아

**Comment by porporpor020202** [comment]
Join페이지 디자인 수정할때, 벨리데이션 로직 개발할때 시뮬레이터에서 접속할때 필요해

**Comment by timepresent95** [comment]
해당 코드를 작업할때만 상태값을 직접 수정을 그냥 하면 되지 않을까 생각했는데
그건 너무 불편하려나?

만약 이게 너무 불편하다면
`if(__DEV__) {}` 내부에 사용해서 개발용으로 사용중인거를 밝히자

**Comment by porporpor020202** [comment]
onboarding에 버튼 만드는게 제일 편했어. 그래야 join페이지 접속이 편해

DEV로 감싸놓을께.
