### ISSUE TITLE
기능추가: eslint 내용 추가 건의

### ISSUE THREAD

**Issue by porporpor020202** [dm-plz/family-farm-mobile#27]
## 정리 설명
*    'react/react-in-jsx-scope': 'off',
위 옵션을 eslint에 추가하고 싶음
## 기대 효과
매번 맨 위에 react 임포트 하지 않아도 됨

**Comment by timepresent95** [comment]
@porporpor020202  좋은것같아! 
이번에 하는 #23 PR 작업에 이것도 같이 추가해서 PR해주면 될것 같아!

추가로 #13 이슈 작업도 부탁할게!!

**Comment by porporpor020202** [comment]
응 같이해서 pr수정해둘께
