### ISSUE TITLE
디자인 수정: USER04 페이지 변경

### ISSUE THREAD

**Issue by timepresent95** [dm-plz/family-farm-mobile#29]
## 변경 사항
USER04 USER05 페이지를 병합하는 과정에서
초대 코드를 모든 사용자가 볼 수 있도록 기획이 수정됨

이에 따라 분기 처리를 제거하면 됨

## 추가 정보
![Screenshot 2024-08-06 at 23 48 51](https://github.com/user-attachments/assets/b4d45c8a-d3df-4429-8b36-658dc0645925)

[Figma1](https://www.figma.com/file/l5vvboNx7unqKHqORUrJq9?embed_host=notion&kind=file&m=dev&node-id=92-1715&t=3rokOnDpj7FApkal-1&viewer=1) [Figma2](https://www.figma.com/file/l5vvboNx7unqKHqORUrJq9?embed_host=notion&kind=file&m=dev&node-id=141-1724&t=3rokOnDpj7FApkal-1&viewer=1)

**Comment by timepresent95** [comment]
@porporpor020202 
지금 당장 작업 안해도 되고
디자이너분이 주말에 디자인 주시면 그때 작업하면 될것같아

**Comment by porporpor020202** [comment]
오 알게쏘

**Comment by timepresent95** [comment]
#63 PR을 통해 해당 작업은 완료되었음
