### ISSUE TITLE
빌드: UUID 설치

### ISSUE THREAD

**Issue by porporpor020202** [dm-plz/family-farm-mobile#36]
## 빌드 설명

uuid 설치
npm install react-native-uuid
https://www.npmjs.com/package/react-native-uuid

## 기대 효과

map 쓸 때, key 생성을 위함

**Comment by porporpor020202** [comment]
안써도 될듯

**Comment by timepresent95** [comment]
map 사용할때가 뭐야?

**Comment by porporpor020202** [comment]
> map 사용할때가 뭐야?

flatList
에서
keyExtractor 속성 쓸때 필요하더라고

**Comment by porporpor020202** [comment]
빼기로 결정~!
