### ISSUE TITLE
버그 수정: 간헐적인 onAnimatedValueUpdate 메세지 출력

### ISSUE THREAD

**Issue by porporpor020202** [dm-plz/family-farm-mobile#46]
## 버그 설명

간헐적으로, IOS 시뮬레이터 상에서 onAnimatedValueUpdate 메시지가 출력 됨.

## 재현 방법
1. 바텀 탭에서 질문답변을 누른다
2. 질문 아무거나 누른다.
3. 답변하기를 누른다
4. 다시 바텀 탭에서 질문 답변을 누른다.
5. 5. 질문 아무거나 누른다.
6. 답변하기를 누른다.
위와 같은 내용을 반복하다보면 간헐적으로 warning 메시지가 출력됨.

## 추가 정보
<img width="288" alt="Screenshot 2024-08-27 at 6 25 25 PM" src="https://github.com/user-attachments/assets/b89b6608-cf68-4f7d-8b63-ad2fef87a250">

**Comment by timepresent95** [comment]
해당 내용을 확인할수 없어 이슈를 닫음
