### ISSUE TITLE
버그 수정: typo 오류

### ISSUE THREAD

**Issue by porporpor020202** [dm-plz/family-farm-mobile#51]
// routes.ts

<img width="419" alt="Screenshot 2024-09-10 at 9 53 40 PM" src="https://github.com/user-attachments/assets/8616f024-4130-46ec-bade-d3a982ddc2eb">

주소가 'auth/oauth/log-in'이 아니라, 'auth/oauth/sign-in'이 아닌지?

**Comment by timepresent95** [comment]
이거 지원이가 log-in으로 준걸거야 api 문서 확인해봐봐

**Comment by porporpor020202** [comment]
<img width="244" alt="Screenshot 2024-09-10 at 10 20 15 PM" src="https://github.com/user-attachments/assets/254cc288-c9a6-47e2-960b-4642388ef39f">
이거랑 다른거야?
API 명세서에는 sign-in인데


<>
이 글 작성하고 난 뒤에 백엔드가 주소를 바꿨어.
({{baseUrl}}/auth/sign-in/oidc)
어차피 추후에 수정해야할듯.

**Comment by porporpor020202** [comment]
<img width="813" alt="Screenshot 2024-09-10 at 10 21 33 PM" src="https://github.com/user-attachments/assets/dbe3fd8e-8181-4670-84cc-d9a744914a7e">
그리고 하나 모르겠는게 있는데, 이거 sign-up 할때 어떤 유저가 sign-up 하는지는 어떻게 알아?

**Comment by timepresent95** [comment]
오케잉 이거 지금 형이 적용해주라~

**Comment by porporpor020202** [comment]
응~

**Comment by timepresent95** [comment]
네비게이션 관리 규칙 변경에 따라 논의를 종료함
