### ISSUE TITLE
버그 수정: 구글 로그인 핸들러 오류

### ISSUE THREAD

**Issue by porporpor020202** [dm-plz/family-farm-mobile#59]
## 버그 설명
발생한 버그에 대한 상세 설명을 작성해주세요.
<img width="699" alt="Screenshot 2024-09-30 at 2 52 57 PM" src="https://github.com/user-attachments/assets/adc53792-535a-4461-a214-48fa83084a3b">

src > pages > Onboarding.tsx 파일에서,
signInWithGoogle() 실행하면, IOS 시뮬레이터가 바로 종료되버림.

## 재현 방법
src > pages > Onboarding.tsx 파일에서,
signInWithGoogle() 실행하면, IOS 시뮬레이터가 바로 종료되버림.

**Comment by timepresent95** [comment]
google client id가 등록되어있지 않아 발생한 문제로 등록을 통해 해결 완료 됨
